name: Deploy Remix Weather App to AKS

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'remix-weather/**'
      - '.github/workflows/deploy.yml'
  push:
    branches: [ main ]
    paths:
      - 'remix-weather/**'
      - '.github/workflows/deploy.yml'

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.REGISTRY }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ env.REGISTRY }}.azurecr.io/remix-weather:$IMAGE_TAG remix-weather
          docker push ${{ env.REGISTRY }}.azurecr.io/remix-weather:$IMAGE_TAG
        env:
          DOCKER_BUILDKIT: 1
